### PR TITLE
updated dependencies to latest, moved to yarn for faster install

### PR DESCRIPTION
**Pull request by Prozi**
yo I checked out this repo and I did what I almost always do
* ncu -a # node check updates
* yarn install
* yarn upgrade
* updated postinstall message

### CODE REVIEW

**Comment by rlindskog** [comment]
@Prozi Thanks for the PR!  Vueniverse does need a dependency bump, but there is a lot more work to be done on the Nuxt side of things.  [Here are the breaking changes](https://nuxtjs.org/guide/release-notes#breaking-changes).

**Comment by Prozi** [comment]
I did run it tho and it did work :P
I'm using nuxt for some time, what specifically needs to be done off the breaking changes' list?

**Comment by rlindskog** [comment]
My bad, I was looking at the demo - path aliases and such.  A couple things for vuetify need to change,`<v-list-item>`, `<v-card-row>` and the color prop for `<v-btn>` don't exist in the new version of vuetify.

**Comment by Prozi** [comment]
oh, so I updated
the demo
the components
gived it a bit different look since I did this from vueniverse example docs

but it has all the previous features (the layout)

also run eslint on demo and template and fixed errors

it should be ok to merge now. regards.

**Comment by Prozi** [comment]
oh and I've just fixed the ~ -> ~/ includes

**Comment by Prozi** [comment]
and fixed those styles again now it really works :)

**Comment by rlindskog** [comment]
@Prozi Thanks so much!!!

**Comment by Prozi** [comment]
no problem it was something I would do anyway and now it has a bigger chance of not disappearing

:smile:

**Pull request merged**
