### PR TITLE
feature: allow to push to heroku out-of-the-box

### PR DESCRIPTION
**Pull request by nenjack**
I added some changes to make project run on heroku

those are:
devDependencies >> dependencies (for running heroku in production mode because it doesnt install devDeps in prod mode)

also process.env.HOST out of app.listen() because then it connects to itself (required for heroku as 0.0.0.0 or localhost dont work afaik)

added mongodb_uri env as its default name for heroku mongolab free addons heroku config

this is a WORK IN PROGRESS
I also gave you push rights to https://vueniverse.herokuapp.com

Known issues:
Sign In doesnt work :(

I'm going to sleep but leaving this here in case someone wants to fight it

to publish to heroku: 
copy demo dir elsewhere 
git init it and 
push to the url

regards, Jacek

### CODE REVIEW

**Comment by rlindskog** [comment]
I like this idea!  Maybe we should just use MONGO_URI instead of DB_URL all together.

**Comment by Prozi** [comment]
I like the idea just keep in mind:

If now.sh doesnt care about the name we can use MONGODB_URI but that
- is heroku specific with specific free addon mongolab free mongodb
- is possibly a breaking change to your template you should notify people about it

**Comment by Prozi** [comment]
also now I veautified the routes ui to somehow more vuetify look I guess (check it out)
in both demo and template

and found a bug which I corrected of controllers.js api route users.get fix when req.params.

I just checked that I didnt break anything and looks ok

I didnt touch the admin route as I dont know how to access it to be honest :)

**Comment by rlindskog** [comment]
NOW doesn't actually have database support, I'm using mongo atlas as my db.  MONGODB_URI should work fine.

It looks good! The profile seems to breaking on page refreshes though, maybe an SSR issue?

**Pull request closed without merging**
